# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

diffusion:
  model: GaussianDiffusion
  test_model: RepaintSpacedDiffusion
  step: 1000
  model_var_type: FIXED_SMALL
  learn_sigma: False
  sampler: 'second-order'
  model_mean_type: EPSILON
  rescale_timestep: False
  loss_type: MSE
  beta_schedule: 'linear'
  scale_ratio: 1.0
  diffusion_learn_sigma: False
  respacing: 10
#  diffusion_model_var_type: LEARNED_RANGE
#  diffusion_loss_type: RESCALED_MSE

#  if diffusion_learn_sigma:
#    diffusion_model_var_type = ModelVarType.LEARNED_RANGE
#    diffusion_loss_type = LossType.RESCALED_MSE

net:
  network: ResUNet
  in_channels: 1
  model_channels: 64
  num_res_blocks: 3
  channel_mult: 1,2,2,2
  attention_resolutions:
  unet_activation:
  weights: checkpoint_ResUNet_iter200000.pth


optimizer:
  optimizer: Adam
  lr: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.999
  lr_decay: False
  weight_decay: 0

  # Scheduler
  scheduler: StepLR
  step_size: 500
  step_gamma: 0.1
  poly_power: 0.9
  exp_gamma: 0.95
  exp_step_size: 445

data:
  dataset: ShapeNetDataset
  train_file:
  data_dir:
  collate_fn:
  input_transform:
  targer_transform:
  cache_data: False
  persistent_workers: False
  suffix: .npy

train:
  max_iter: 270000
  is_train: True
  stat_freq: 50
  val_freq: 10000
  empty_cache_freq: 1
  train_phase: train
  overwrite_weights: False
  resume: True
  resume_optimizer: True
  eval_upsample: False
  lenient_weight_loading: False
  mix_precision: True
  use_gradient_clip: False
  gradient_clip_value: 1.0

# Test
test:
  partial_shape:
  test_cnt: 160
  clip_noise: False
  use_ddim: False
  ddim_eta: 1.0
  test_phase: test
  test_batch_size: 4


# Misc
misc:
  seed: 123

exp:
  res: 32
  representation: sdf

  batch_size: 64
  num_gpus: 1
  num_workers: 0

  skip_validate: True
  log_dir: exps/default


################################################################################
# slurm parameters
################################################################################
defaults:
  - hydra/launcher: submitit_slurm
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ${exp.log_dir}
  sweep:
    dir: ${exp.log_dir}
  launcher:
    partition: dev
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: ${hydra.job.name}
    timeout_min: 4320
    cpus_per_task: 24
    gpus_per_node: ${exp.num_gpus}
    tasks_per_node: 1
    mem_gb: 256
    nodes: 1
    constraint:
    exclude: seti
    max_num_timeout: 3



